### ISSUE TITLE
When the listening port is set to "8080" in the environment variable, vince crashes and the vince image runs directly

### ISSUE THREAD

**Issue by aaro-n** [vinceanalytics/vince#73]
# Configuration Files
### Dockerfile
```
FROM ghcr.io/vinceanalytics/vince
CMD ["serve"] 
```
###  docker-compose.yml
```
services:
  vince:
    container_name: vince
    build:
      context: . 
    environment:
      - VINCE_LISTEN="8080" 
      - VINCE_ADMIN_NAME="acme"
      - VINCE_ADMIN_PASSWORD="1234" 
    ports:
      - "18886:8080"
    volumes:
      - ./data:/vince-data
    restart: unless-stopped
```
# question
1.  When the environment variable is VINCE_LISTEN="8080", the container crashes
2.  log
```
www@VM-0-15-debian:~/vince$ cat docker-compose.yml 
services:
  vince:
    container_name: vince
    build:
      context: . 
    environment:
      - VINCE_LISTEN="8080" 
      - VINCE_ADMIN_NAME="acme"
      - VINCE_ADMIN_PASSWORD="1234" 
    ports:
      - "18886:8080"
    volumes:
      - ./data:/vince-data
    restart: unless-stopped

www@VM-0-15-debian:~/vince$ docker-compose up --build
Creating network "vince_default" with the default driver
Building vince
Sending build context to Docker daemon  53.43MB
Step 1/2 : FROM ghcr.io/vinceanalytics/vince
 ---> 05d3f072016e
Step 2/2 : CMD ["serve"]
 ---> Using cache
 ---> edd0a096e4ae
Successfully built edd0a096e4ae
Successfully tagged vince_vince:latest
Creating vince ... done
Attaching to vince
vince    | 2025/05/13 15:14:44 [JOB 1] WAL 000002 stopped reading at offset: (data/000002.log: 0); replayed 0 keys in 0 batches
vince    | 2025/05/13 15:14:44 INFO unpacking geo database path=vince-data/city.mmdb
vince    | 2025/05/13 15:14:44 INFO unpacked geo database size_in_mb=108
vince    | 2025/05/13 15:14:44 INFO loading translation data
vince    | 2025/05/13 15:14:44 INFO complete loading translation elapsed=585.726µs keys=0
vince    | 2025/05/13 15:14:44 INFO starting event processing loop
vince    | 2025/05/13 15:14:44 INFO starting server addr="\"8080\""
vince    | 2025/05/13 15:14:44 INFO Shutting down
vince    | 2025/05/13 15:14:44 INFO exiting event processing loop
vince    | 2025/05/13 15:14:45 [JOB 1] WAL 000002 stopped reading at offset: (data/000002.log: 0); replayed 0 keys in 0 batches
vince    | 2025/05/13 15:14:45 INFO loading translation data
vince    | 2025/05/13 15:14:45 INFO complete loading translation elapsed=65.353µs keys=0
vince    | 2025/05/13 15:14:45 INFO starting server addr="\"8080\""
vince    | 2025/05/13 15:14:45 INFO starting event processing loop
vince    | 2025/05/13 15:14:45 INFO exiting event processing loop
vince    | 2025/05/13 15:14:45 INFO Shutting down
vince exited with code 0
```

3. Allow the container to run directly without adding commands. The Dockerfile file must add "CMD ["serve"]" so that the container can run directly.
